### PR TITLE
Fix compilation without PCH

### PR DESCRIPTION
**Pull request by aganea**
I had to make a few changes while integrating this in our UE 5.3.2 codebase.

### CODE REVIEW

**Comment by Zeblote** [comment]
Hmm, I'm curious why this is necessary. We are also using 5.3.2 and it works fine for us. Did you make changes to the build configuration for your project?

**Comment by aganea** [comment]
@Zeblote Yes, I wonder if it's us disabling PCH that causes this. We're building with:
```
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
    <BuildConfiguration>
        <bDeterministic>true</bDeterministic>
        <CppStandard>Cpp20</CppStandard>
        <bUsePCHFiles>false</bUsePCHFiles>
    </BuildConfiguration>
    <WindowsPlatform>
        <Compiler>Clang</Compiler>
        <bUpdatedCPPMacro>true</bUpdatedCPPMacro>
        <bStrictConformanceMode>true</bStrictConformanceMode>
        <bAllowClangLinker>true</bAllowClangLinker>
    </WindowsPlatform>
</Configuration>
```
Also we validate with `<bUseUnityBuild>false</bUseUnityBuild>` occasionally.

**Comment by Zeblote** [comment]
I see, that makes sense with the no PCH build, we don't normally use that. I think there's a mistake in your version though - you have AllowWindowsPlatformTypes chained directly before HideWindowsPlatformTypes, normally these are wrapped around the third party include, aren't they?

**Comment by aganea** [comment]
I reverted some of the changes you mentioned, they don't seem required.

**Pull request merged**
